"""add colum number model users

Revision ID: 1c2741ff5de2
Revises: 822d6a7580d3
Create Date: 2026-06-04 08:20:28.123882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c2741ff5de2'
down_revision: Union[str, Sequence[str], None] = '822d6a7580d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'number')
    # ### end Alembic commands ###
